/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ZhRouteImport } from './routes/zh'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as KoRouteImport } from './routes/ko'
import { Route as EnRouteImport } from './routes/en'
import { Route as IndexRouteImport } from './routes/index'

const ZhRoute = ZhRouteImport.update({
  id: '/zh',
  path: '/zh',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const KoRoute = KoRouteImport.update({
  id: '/ko',
  path: '/ko',
  getParentRoute: () => rootRouteImport,
} as any)
const EnRoute = EnRouteImport.update({
  id: '/en',
  path: '/en',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/en': typeof EnRoute
  '/ko': typeof KoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/zh': typeof ZhRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/en': typeof EnRoute
  '/ko': typeof KoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/zh': typeof ZhRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/en': typeof EnRoute
  '/ko': typeof KoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/zh': typeof ZhRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/en' | '/ko' | '/sitemap.xml' | '/zh'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/en' | '/ko' | '/sitemap.xml' | '/zh'
  id: '__root__' | '/' | '/en' | '/ko' | '/sitemap.xml' | '/zh'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EnRoute: typeof EnRoute
  KoRoute: typeof KoRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ZhRoute: typeof ZhRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/zh': {
      id: '/zh'
      path: '/zh'
      fullPath: '/zh'
      preLoaderRoute: typeof ZhRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ko': {
      id: '/ko'
      path: '/ko'
      fullPath: '/ko'
      preLoaderRoute: typeof KoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en': {
      id: '/en'
      path: '/en'
      fullPath: '/en'
      preLoaderRoute: typeof EnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EnRoute: EnRoute,
  KoRoute: KoRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ZhRoute: ZhRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
